"""empty message

Revision ID: 63109fe95d92
Revises: c42afa98933e
Create Date: 2025-05-14 11:37:05.085501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63109fe95d92'
down_revision: Union[str, None] = 'c42afa98933e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    # ### end Alembic commands ###
